### PR TITLE
Add section on thamos images

### PR DESCRIPTION
**Pull request by mayaCostantini**
Add section about the `thamos images` command and Thoth's recommendations for container image security.

### CODE REVIEW

**Review by fridex — APPROVED** [review]
very nice, looks good to me 👍🏻

**Comment by mayaCostantini** [comment]
> very nice, looks good to me 👍🏻

Thanks! :100: I was just wondering if the content was detailed enough and if we had any output example available for the `thamos images` command?

**Comment by fridex** [comment]
> > very nice, looks good to me 👍🏻
> 
> Thanks! 100 I was just wondering if the content was detailed enough and if we had any output example available for the `thamos images` command?

The stage environment has some images registered. The listing of container images might be too large though.

**Comment by mayaCostantini** [comment]
> The listing of container images might be too large though.

Ok, so let's keep it as it is if you are ok with it. Don't hesitate if you think the section deserves more explanations on how the resolution process works for container images, I haven't gone into much detail because I didn't want to repeat the articles content, but I can add them as references.

**Comment by fridex** [comment]
+1, sounds good to me

**Pull request merged**
